import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Glam signature perfume",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "R499.00",
    newPrice: "R350.00",
    flavor: "floral",
    category: "perfumes",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Glam gorgeous huns",
    star: <AiFillStar className="rating-star" />,
    reviews: "(111 reviews)",
    prevPrice: "R600.00",
    newPrice: "R400.00",
    flavor: "sweet",
    category: "perfumes",
  },

  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Glam choc",
    star: <AiFillStar className="rating-star" />,
    reviews: "(92 reviews)",
    prevPrice: "R480",
    newPrice: "R280.00",
    flavor: "chocolaty",
    category: "perfumes",
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Glam sportage",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "R700.00",
    newPrice: "R500.00",
    flavor: "wood",
    category: "perfumes",
  },
  {
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Glam mascara",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "R80.00",
    newPrice: "R75.00",
    category: "make-up",
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Glam lip gloss",
    star: <AiFillStar className="rating-star" />,
    reviews: "(200 reviews)",
    prevPrice: "R100",
    newPrice: "R75",
    color: "red",
    category: "make-up",
  },

  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Eyeshadow palets",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "R150",
    newPrice: "R120",
    category: "make-up",
  },

  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Glam lashes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(125 reviews)",
    prevPrice: "R140,00",
    newPrice: "R175,00",
    category: "make-up",
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Glam lipstick",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "R140,00",
    newPrice: "R200",
    category: "make-up",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Glam foundation",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "R140,00",
    newPrice: "R150",
    category: "make-up",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "R140,00",
    newPrice: "R150",
    color: "gold",
    category: "jewellery",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Glam earrings",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "R140,00",
    newPrice: "R150",
    color: "gold",
    category: "jewellery",
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Glam earrings",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "R140,00",
    newPrice: "R150",
    color: "silver",
    category: "jewellery",
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Glam necklace",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "R140,00",
    newPrice: "R150,00",
    color: "silver",
    category: "jewellery",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Glam Rings",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "R140,00",
    newPrice: "R100,00",
    color: "gold",
    category: "jewellery",
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Glam watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "$160,00",
    newPrice: "R100",
    color: "black",
    category: "jewellery",
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Glam bracelet",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "R140,00",
    newPrice: "R100,00",
    color: "gold",
    category: "jewellery",
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Glam Hair",
    star: <AiFillStar className="rating-star" />,
    reviews: "(130 reviews)",
    prevPrice: "$1600,00",
    newPrice: "R1500,00",
    color: "black",
    category: "Hair",
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Glam curly hair",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "R1400,00",
    newPrice: "R1300,00",
    color: "black",
    category: "Hair",
  },
  {
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Glam bob wig",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "R1400,00",
    newPrice: "R1500,00",
    color: "black",
    category: "Hair",
  },
  {
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Glam silky scarf",
    star: <AiFillStar className="rating-star" />,
    reviews: "(133 reviews)",
    prevPrice: "R140,00",
    newPrice: "R100,00",
    color: "black",
    category: "Hair",
  },
  {
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "Glam nail sets",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "R140,00",
    newPrice: "R150,00",
    color: "pink",
    category: "nails",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "slay nail sets",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "R140,00",
    newPrice: "R200",
    color: "red",
    category: "nails",
  },

  {
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "shades",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "R200,00",
    newPrice: "R220,00",
    color: "black",
    category: "sunglasses",
  },
  {
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "shady shades",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "R140,00",
    newPrice: "R170",
    color: "black",
    category: "sunglasses",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Glam eyebrow pencil",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "R140,00",
    newPrice: "R150,00",
    color: "brown",
    category: "make-up",
  },
  {
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Dramatic lashes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(133 reviews)",
    prevPrice: "R140,00",
    newPrice: "R150",
    color: "black",
    category: "make-up",
  },
  {
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Glam make-up remover",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "R230,00",
    newPrice: "R150",
    category: "make-up",
  },
];

export default data;